### PR TITLE
Issue #2926905: Disable caching on CiviCRM paths with i18n prefixes.

### PR DESCRIPTION
**Pull request by mlutfy**
https://www.drupal.org/project/provision/issues/2926905

### CODE REVIEW

**Comment by omega8cc** [comment]
Honestly, I'm not in favor of replacing the much faster `location ^~` with simple `location ~*` wildcard. It may seem not very relevant until you see the rewrites flood Nginx is doing if you are using wildcard instead of "stop here" matching `location ^~`

We are trying to use `location ^~` everywhere we can, for obvious performance reasons, and CiviCRM generates a ton of such requests, so I would rather propose to add i18n location *below* current location, so it will work only for i18n prefixes. Then you don't need the `?` and `location ~* ^/\w\w/civicrm {` is enough, as proposed on https://www.drupal.org/project/provision/issues/2926905

**Comment by omega8cc** [comment]
We will propose a patch, but next week, if you allow.

**Comment by omega8cc** [comment]
Proposed patch posted at https://www.drupal.org/project/provision/issues/2926905#comment-12436499

**Comment by mlutfy** [comment]
Closing this PR, since a patch was merged on d.o.

**Pull request closed without merging**
